### ISSUE TITLE
Right way to use pool worker option in sidekiq job

### ISSUE THREAD

**Issue by bagiojm** [benngarcia/rails_async_methods#6]
I am trying to invoke a sidekiq job from rails, I have tried passing "pool" worker option for sidekiq job, but somehow perform_async ignores this option and passes the job to default config sidekiq has been initialised with..

REDIS = ConnectionPool.new { Redis.new(url: '<value>', namespace: '<value>') }
Sidekiq::MyWorker.set("pool" => REDIS).perform_async(<args>)

Am I doing this right way?

**Comment by benngarcia** [comment]
Unfortunately [ActiveJob doesn't support a couple of sidekiq options](https://github.com/sidekiq/sidekiq/issues/4281
). `pool` is one of those options.

This is the second issue raised for this library regarding ActiveJob not passing sidekiq options. I'm planning on seeing if I can add a feature flag on the library to pass additional options through to sidekiq, though feel free to look into it yourself in the meantime 👍
